FROM tensorflow/tensorflow:2.2.3-py3

# Install system packages
RUN apt-get update && apt-get install -y \
      ffmpeg

RUN rm -rf /var/lib/apt/lists/*

COPY /src/requirements.txt requirements.txt

RUN pip install --upgrade pip==21.1.3 && \
    pip install -r requirements.txt

COPY src /src
COPY entrypoints /src/entrypoints
WORKDIR /src

ENV PYTHONPATH='/src/:$PYTHONPATH'

ENTRYPOINT ["entrypoints/entrypoint.train.cpu.sh"]
