FROM tensorflow/tensorflow:2.2.3-py3

# Install system packages
RUN apt-get update && apt-get install -y \
    ffmpeg --no-install-recommends && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY /src/requirements.txt requirements.txt

RUN pip install --upgrade pip==21.1.3 && \
    pip install --no-cache-dir -r requirements.txt

WORKDIR /src

COPY src /src
COPY entrypoints /src/entrypoints

ENV PYTHONPATH='/src/:$PYTHONPATH'

ENTRYPOINT ["entrypoints/entrypoint.train.cpu.sh"]
